path: jdbc:mysql://dam2.mysql.iesquevedo.es:3335/
database: AlejandroMarino_Restaurant?useSSL=false
user_name: root
dB_password: quevedo2dam
driver: com.mysql.cj.jdbc.Driver
paidOrders: data/paidOrders.xml