version: '3.1'
services:
  web:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - /C/Users\2dam\documents/MarinoRepositorio/gEmpresas/odoo/odooodoo-web-data:/var/lib/odoo
      - /C/Users/2dam/documents/MarinoRepositorio/gEmpresas/odoo/config:/etc/odoo
      - /C/Users/2dam/documents/MarinoRepositorio/gEmpresas/odoo/addons:/mnt/extra-addons
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo